[package]
name = "ratatosk-resp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ratatosk-core = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
smallvec = { workspace = true }
itoa = { workspace = true }
memchr = { workspace = true }
